repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.1
  hooks:
  - id: black
    args: ["--check", "--diff"]
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: ["--configfile=bandit.yaml"]
