name: Build, Publish & Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build_publish_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install poetry, build, publish to PyPI
      id: build_publish
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        poetry build
        poetry publish --username=${{ secrets.PYPI_USERNAME }} --password=${{ secrets.PYPI_PASSWORD }}
        echo "::set-output name=VERSION::$(poetry version --short)"
        echo "::set-output name=WHEEL_PATH::$(ls -1r dist/* | head -n 1)"

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: version ${{ steps.build_publish.outputs.VERSION }}
        files: ${{ steps.build_publish.outputs.WHEEL_PATH }}
