name: Build, Publish & Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build_publish_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install poetry, build
      id: build
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry build
        echo "VERSION=$(poetry version --short)" >> $GITHUB_OUTPUT

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: version ${{ steps.build.outputs.VERSION }}
        files: 'dist/*'
